name: cd
on:
  push:
    branches:
      - master
      
  workflow_dispatch:

env:
  HYDRO_SERVING_REPO: ${{ secrets.HYDRO_SERVING_REPO }}
  IMAGE: ${{ secrets.IMAGE_NAME }}
  
jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
      
    - name: Restore cache
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}
        
    - name: Build image
      run: "sbt -DappVersion=${{ github.sha }} docker"
      
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Retag image
      run: "docker tag hydrosphere/${{ env.IMAGE }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:${{ github.sha }}"
      
    - name: Push image
      run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:${{ github.sha }}"
      
    - name: Upload docker image artifact
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "hydrosphere/${{ env.IMAGE }}:${{ github.sha }}"
        
    - name: Update image version in hydro-serving repo
      if: github.event_name == 'push'
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: "Local release"
        token: ${{ secrets.HYDRO_SERVING_TOKEN }}
        repo: ${{ env.HYDRO_SERVING_REPO }}
        inputs: '{"service_image_name":"${{ env.IMAGE }}", "registry_url":"${{ secrets.DOCKERHUB_USERNAME }}", "tag":"${{ github.sha }}"}'
      
  Release:
    needs: [Build_and_publish]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Bump version
        id: bump
        uses: codacy/git-version@2.4.0
        
      - name: Docker Image Artifact Download
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "hydrosphere/${{ env.IMAGE }}:${{ github.sha }}"
          
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Retag image
        run: "docker tag hydrosphere/${{ env.IMAGE }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:v${{ steps.bump.outputs.version }}"
      
      - name: Push image
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:v${{ steps.bump.outputs.version }}"
          
      - name: Tag commit
        run: "git tag v${{steps.bump.outputs.version}}"
        
      - name: Push tag
        run: "git push --tags"
        # TODO: update grpc version
        
   
   
